import 'package:flutter/material.dart';
import '../../helpers/aboutUsContent.dart';

class FoodLicensePage extends StatelessWidget {
  const FoodLicensePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text("Food License")),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(15),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              getParagraph(
                  "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the website www.hibachi.in."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "www.hibachi.in (hereinafter referred to as “Website”) is the exclusive property of HIBACHI GOURMET PRIVATE LIMITED with its registered office at # Flat No. 305, Sy No. 37 & 38, Plot No.336, Sree Nilayam, Manikonda, Hyderabad – 500089, Telangana, India"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Your use of the Website is governed by the following terms and conditions (“Terms of Use”) as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If you browse, access, secure access to the Website, You shall be subject to all the policies and terms mentioned herein. By merely accessing or securing access, browsing the Website, You shall be contracting with www.hibachi.in, HIBACHI GOURMET PRIVATE LIMITED and these terms and conditions including the policies constitute your binding obligations, with www.hibachi.in, HIBACHI GOURMET PRIVATE LIMITED."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "For the purpose of these Terms of Use, wherever the context so requires ‘You’ or “User” shall mean any natural or legal person browsing, accessing or who has registered on the Website by providing Registration Data while registering on the Website as Registered User using Computer, Mobile phones, Tablets."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "www.hibachi.in allows users to surf, browse the Website without registering on the Website. The term “we”, “us”, “our” shall HIBACHI GOURMET PRIVATE LIMITED"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to you. It is your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website, following the posting of changes shall indicate your consent and acceptance to such revisions"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter, access, use the Website."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "ACCESSING, BROWSING THE WEBSITE, REGISTERING ON THE WEBSITE INDICATE YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS, SO PLEASE READ THE TERMS AND CONDITIONS CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by the Privacy Policy and legal policies mentioned on www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              //ONLINE PLATFORM
              getHeader("ONLINE PLATFORM"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "HIBACHI GOURMET PRIVATE LIMITED is an intermediary and offers an online platform through the Website (www.hibachi.in). The online platform www.hibachi.in offers various categories of fresh chicken, meat, fish, prawns, eggs, pickles. The online platform www.hibachi.in is designed in a manner to deliver such fresh meat, chicken, prawns, eggs, pickles etc. at the convenience of your doorstep. The online platform enables you to place orders for the above through the website www.hibachi.in and facilitates the delivery of such orders to your locations."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You understand, acknowledge and accept that the online platform i.e. www.hibachi.in is only a mere facilitator."),
              SizedBox(
                height: 10,
              ),
              //ORDERS – CALL CENTRE
              getHeader("ORDERS – CALL CENTRE"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You may also place your orders through our Hibachi Call Centre – PLS MENTION THE NUMBER. You herein agree that these terms and conditions and policies mentioned on www.hibachi.in shall be applicable for all orders placed through our Call Centre. We shall deliver your orders placed through our Call Centre as per your location and delivery slot opted thereof."),
              SizedBox(
                height: 10,
              ),
              //TERMS OF USE
              getHeader("TERMS OF USE"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "This Website (www.hibachi.in) shall be used only by persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use this Website (www.hibachi.in). If you are a minor i.e. under the age of 18 years, you shall not register as a member of the Website (www.hibachi.in) and shall not use Website (www.hibachi.in). As a minor if you wish to use or transact on Website (www.hibachi.in), such use may be made by your legal guardian or parents on the Website (www.hibachi.in). The Website (www.hibachi.in) reserves the right to terminate your Registration and / or refuse to provide you with access to the Website (www.hibachi.in) if it is brought to the Website‘s notice or if it is discovered that you are under the age of 18 years."),
              SizedBox(
                height: 10,
              ),
              //REGISTRATION & NO CHARGES
              getHeader("REGISTRATION & NO CHARGES"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "he website does not charge any fee for browsing, creating an account on the Website (www.hibachi.in). In particular, www.hibachi.in may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website (www.hibachi.in). In such an event, the website reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Website (www.hibachi.in) and such changes shall automatically become effective immediately after they are posted on the Website (www.hibachi.in). Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              //WEBSITE (www.hibachi.in)’s TERMS OF USE
              getHeader("WEBSITE (www.hibachi.in)’s TERMS OF USE"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You agree, undertake and confirm that your use of Website (www.hibachi.in) shall be strictly governed by the following binding principles. You hereby agree not to use the Website (www.hibachi.in) to:-"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(a) harass or advocate harassment of another person;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(b) involve the transmission of “junk mail”, “chain letters”, or unsolicited mass mailing or “spamming”;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(c) promote illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "d) infringe upon or violates any third party’s rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person’s name, email address, physical address or phone number) or rights of publicity];"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(e) promote an illegal or unauthorized copy of another person’s copyrighted work such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(f) provide material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(g) provide instructional information about illegal activities such as making or buying illegal weapons, violating someone’s privacy, or providing or creating computer viruses;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(h) upload, share, transmit video, photographs, or images of another person (with a minor or an adult)."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(i) to gain or attempt to gain unauthorized access or exceeds the scope of authorized access to the Website (www.hibachi.in) or to account information or other areas of the Website (www.hibachi.in ) or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(j) engage in commercial activities and/or sales without our prior written consent of the Website such as contests, sweepstakes, barter, advertising and pyramid schemes etc. related to the Website (www.hibachi.in). Throughout this Terms of Use, ,www.hibachi.in‘s prior written consent means a communication coming from www.hibachi.in ‘s Legal Department, categorically in response to your request, and categorically addressing the activity or conduct for which you seek authorization;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(k) solicit gambling or engage in any gambling activity which We, in Our sole discretion, believe is or could be construed as being illegal;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(l) interfere with another user’s use and enjoyment of the Website (www.hibachi.in) or any other individual’s user and enjoyment of similar services;"),
              SizedBox(
                height: 10,
              ),
              getParagraph("(m) harm minors in any way;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(n) infringe any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen items including images, pictures, information, data;"),
              SizedBox(
                height: 10,
              ),
              getParagraph("(o) violate any law for the time being in force;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(p) spread, transmit, upload software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(q) threaten the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(r) to offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "(s)You shall not create liability for us or cause us to lose (in whole or in part) the services of our ISPs or any third parties including individuals, companies, entities, organisations etc"),
              SizedBox(
                height: 10,
              ),
              //PROHIBITED USE OF WEBSITE (www.hibachi.in)
              getHeader("PROHIBITED USE OF WEBSITE (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "1. You shall not use any “deep-link”, “page-scrape”, “robot”, “spider” or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website (www.hibachi.in) or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website (www.hibachi.in) or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website (www.hibachi.in). We reserve our right to bar any such activity."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "2. You shall not attempt to gain unauthorized access to any portion or feature of the Website (www.hibachi.in), or any other systems or networks connected to the Website (www.hibachi.in) or to any server, computer, network, or to any of the services offered on or through the Website (www.hibachi.in), by hacking, password “mining” or any other illegitimate means."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "3. You shall not probe, scan or test the vulnerability of the Website (www.hibachi.in) or any network connected to the Website (www.hibachi.in) nor breach the security or authentication measures on the Website (www.hibachi.in) or any network connected to the Website (www.hibachi.in). You may not reverse look-up, trace or seek to trace any information on any other user of Website (www.hibachi.in), or any other customer, including any account on the Website (www.hibachi.in) not owned by You, to its source, or exploit the Website (www.hibachi.in) or any service or information made available or offered by or through the Website (www.hibachi.in), in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Website (www.hibachi.in)."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "3. You shall not probe, scan or test the vulnerability of the Website (www.hibachi.in) or any network connected to the Website (www.hibachi.in) nor breach the security or authentication measures on the Website (www.hibachi.in) or any network connected to the Website (www.hibachi.in). You may not reverse look-up, trace or seek to trace any information on any other user of Website (www.hibachi.in), or any other customer, including any account on the Website (www.hibachi.in) not owned by You, to its source, or exploit the Website (www.hibachi.in) or any service or information made available or offered by or through the Website (www.hibachi.in), in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Website (www.hibachi.in)."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "5. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website (www.hibachi.in) or any transaction being conducted on the Website (www.hibachi.in) or with any other person’s use of the Website (www.hibachi.in)."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "6. You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal, you send to us on or through the Website (www.hibachi.in) or any service offered on or through the Website (www.hibachi.in). You may not pretend that you are, or that you represent, someone else, or impersonate any other individual or entity."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "7. You may not use the Website (www.hibachi.in) or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of HIBACHI GOURMET PRIVATE LIMITED , Website (www.hibachi.in) and / or others."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "8. You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules there under as applicable and as amended from time to time and also all applicable laws, rules and regulations."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "9. You may not transmit any chain letters or unsolicited commercial or junk email to other users via the Website (www.hibachi.in)."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "10. It shall be a violation of these Terms of Use to use any information obtained from the Website (www.hibachi.in) in order to harass, abuse, or harm another person, or solicit, or sell to another person including but not limited to individuals, entities, companies, organisations any such information."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "11. You understand that we have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website (www.hibachi.in) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, we can (and You hereby expressly authorize us to) disclose any information about You to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "12. We reserve the right, but has no obligation, to monitor the materials posted on the Website (www.hiabchi.in) The Website (www.hibachi.in) shall have the right to remove or edit any content, product, image that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "13. It is possible that other Users (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on the Website (www.hibachi.in) and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about you due to your use of the Website (www.hibachi.in), and that the recipient may use such information to harass or injure you. We does not approve of such unauthorized uses, but by using the Website (www.hibachi.in) You acknowledge and agree that we are not responsible for the use of any personal information that You publicly disclose or share with others on the Website (www.hibachi.in)."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "14. The Website (www.hibachi.in) shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services)."),
              SizedBox(
                height: 10,
              ),
              //CONTENTS POSTED ON THE WEBSITE
              getHeader("CONTENTS POSTED ON THE WEBSITE"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The Platform description, Content, text, user interfaces, visual iinterfaces, photographs, images, pictures, trademarks, logos, and artwork relating to the Website (www.hibachi.in) shall be the sole property of HIBACHI GOURMET PRIVATE LIMITED and we have worldwide, perpetual and transferable rights in regard to such Content. We shall be entitled to, consistent with our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "All the intellectual property, proprietary rights arising out of any “Third Party Content” including but not limited to articles, recipes, blogs, images etc. shall be the exclusive property of the respective intellectual property owners. We have no intention to acquire the intellectual property arising out of Third Party Content. In no event, shall HIBACHI GOURMET PRIVATE LIMITED, Website (www.hibachi.in) hold any responsibility, liability for such Third-Party Content."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The Website (www.hibachi.in) may also contain free images from the internet, images legally outsourced from various sources, royalty free images and in such case, the source of the images may also be mentioned and credit shall be given to the respective intellectual property owner."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Nothing contained herein shall be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, Website (www.hibachi.in) or other medium for publication or distribution or for any commercial enterprise, without the express prior written consent of HIBACHI GOURMET PRIVATE LIMITED , Website (www.hibachi.in)."),
              SizedBox(
                height: 10,
              ),
              //LIABILITY DUE TO INTERNET CONNECTIVITY & NETWORK ISSUES
              getHeader(
                  "LIABILITY DUE TO INTERNET CONNECTIVITY & NETWORK ISSUES"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The Website (www.hibachi.in), HIBACHI GOURMET PRIVATE LIMITED shall hold no responsibility, liability for any actions, acts including but not limited to errors, transmission, activities and issues arising out of internet connectivity and any other network related issues."),
              SizedBox(
                height: 10,
              ),
              //REVIEW POLICY
              getHeader("REVIEW POLICY"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "While we encourage you to share your views and opinions on the Website (www.hibachi.in), we expect that this will be done in a respectful manner. This policy is applicable to posts, comments and reviews posted by you on and/or using Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The Website (www.hibachi.in) shall however not agree with or endorse every comment that individuals post on the Website (www.hibachi.in). When making moderation decisions, we will take these guidelines, as well as the context in which comments are made, into account"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We share this information in an effort to be transparent about our moderation process and why certain comments may be removed. Kindly read these terms/ guidelines while making any posts, comments, reviews on the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You specifically agree not to post or transmit any comments, reviews, posts, content or engage in any activity that: –"),
              SizedBox(
                height: 10,
              ),
              getParagraph("1. Violate our Terms and Policies;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "2. Is harmful, threatening, abusive, harassing, tortious, indecent, defamatory, discriminatory, vulgar, profane, obscene, libelous, hateful or otherwise objectionable"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "3. Violate any right, including, but not limited to, right of privacy, right of publicity, copyright, trademark, patent, trade secret, or any other intellectual property or proprietary rights;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "4. Disguising or attempting to disguise the origin of your comment, review, posts, content including but not limited to by submitting your comments, posts, reviews, content under a fake or false name"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "5. Constitutes a knowingly erroneous or unethical review"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "6. Causes, or is a result of, a conflict of interest;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "7. Is commercial in nature, including but not limited to posts, comments, reviews submitted in exchange for payment,"),
              SizedBox(
                height: 10,
              ),
              getParagraph("8. Contains material that is not in English"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "9. Accesses or uses the account of another user without permission;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "10. We reserve the right to remove any comment, review, posts, content that might be found extremely offensive or threatening."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "11. Please don’t exaggerate, falsely state, misrepresent your experience and watch your language."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "12. This also includes but not is limited to derogatory comments or indication of a personal vendetta against Website (www.hibachi.in), HIBACHI GOURMET PRIVATE LIMITED and its affiliates."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "All links posted as comments, reviews on the Website will be reviewed and may be deleted if found violating these guidelines. Repeated violations of this policy may cause the author to be blocked from our Website (www.hibachi.in)."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The Website (www.hibachi.in) shall have the right to immediately block your access and further it shall also have the right to remove any non-compliant comment, post, review and content forthwith, uploaded on the Website. The Website reserves have the right to take appropriate recourse to such remedies as would be available to it under various statutes."),
              SizedBox(
                height: 10,
              ),
              //USER OBLIGATIONS
              getHeader("USER OBLIGATIONS"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "1. You shall be obliged to provide accurate information and other details to us"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "2. You shall also adhere to the minimum age requirement i.e. 18 years as defined by the law of the land"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "3. You shall read all the policies, terms mentioned in the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "4. You shall not copy or use the information contained in the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "5. You shall ensure compliance to the User Review policy contained herein"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "6. You shall be responsible for all and acts arising out of your account"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "7. You shall be responsible for ensuring reasonable security measures regarding your login credentials and in event shall the Website, HIBACHI GOURMET PRIVATE LIMITED be responsible or liable in this regard"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "8. You shall be responsible in full and complete for any and all orders placed through your account on the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "9. You shall be responsible for making the payment in full and complete for any and all orders you place through your account on the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "10. You shall be responsible for providing complete and accurate information including the details of your location, address, phone no etc. so as to enable us to deliver your order(s) at your doorstep"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "11. You shall be able to schedule your orders, browse your order history, send referral codes and offers to your friends or contacts, view articles, blogs, recipes and review or comment on the same"),
              SizedBox(
                height: 10,
              ),
              //PRIVACY
              getHeader("PRIVACY"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We view protection of Your privacy as a very important principle. We understand clearly that You and Your Sensitive Personal Information is one of our most important assets. We store and process Your Sensitive Personal Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our Privacy Policy is available for more details."),
              SizedBox(
                height: 10,
              ),
              getHeader("LEGAL DISCLAIMERM"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "This Website (www.hibachi.in), all the services, included on or otherwise made available to You through this Website (www.hibachi.in) are provided on “as is” and “as available” basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, the Website does not warrant that: –"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "i. This Website (www.hibachi.in) will be constantly available, or available at all; or the information on this Website (www.hibachi.in) is complete, true, accurate or non-misleading."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "ii. The Website (www.hibachi.in) does not warrant that this site; information, Content, materials, images, Data, Information, Pricing Information (including software) or services included on or otherwise made available to You through the Website (www.hibachi.in); their servers; or electronic communication sent from us are free of viruses or other harmful components."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Nothing on Website (www.hibachi.in) constitutes, or is meant to constitute, advice of any kind."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We disclaim any damages, liabilities, loss, claims including ANY SPECIAL, INCIDENTAL, INDIRECT or CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION OR ARISING OUT OF YOUR USE OF THE WEBSITE."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You will be required to enter a valid name, phone number and email id while availing registering on the Website (www.hibachi.in). By registering your phone number, email with us, you consent to be contacted by us via phone calls and / or SMS notifications and/ or email, in case of any updates."),
              SizedBox(
                height: 10,
              ),
              //INDEMNITY
              getHeader("INDEMNITY"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You shall indemnify and hold harmless the Website (www.hibachi.in), HIBACHI GOURMET PRIVATE LIMITED , its Director, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions, damage claims made by any third party including third party vendor, user or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party."),
              SizedBox(
                height: 10,
              ),
              //APPLICABLE LAW / JURISDICTION
              getHeader("APPLICABLE LAW / JURISDICTION"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Hyderabad"),
              SizedBox(
                height: 10,
              ),
              //DESCRIPTION
              getHeader("DESCRIPTION"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The Website (www.hibachi.in) does not ensure that the content including description, data and information thereof is accurate, complete, reliable, current, or error-free and assumes no liability in this regard."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The Website (www.hibachi.in) may include inaccuracies and typographical errors. Changes and improvements are periodically made to the site and the information therein. We do not warrant or assume any legal liability or responsibility for the completeness, or usefulness of any information, content, blogs etc."),
              SizedBox(
                height: 10,
              ),
              getHeader("DELIVERY POLICY"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "All the products purchased or ordered through the Website (www.hibachi.in) shall be delivered based on the pin-code and location entered by You on accessing the website (www.hibachi.in) and placing the order thereof. However, the delivery time and charges if any shall be notified upon checkout or completion of your order. Further, the delivery time and charges if any shall depend on the product you order."),
              SizedBox(
                height: 10,
              ),
              //NOTIFICATION OF SHIPMENT
              getHeader("NOTIFICATION OF SHIPMENT"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "In case an order is placed through the website (www.hibachi.in), we shall send information to You through email and SMS (email id, mobile no provided by You during checkout or registration) notifying the details of Shipment regarding your order. This also includes the name of the logistic partner, tracking number and the date of delivery regarding Your order."),
              SizedBox(
                height: 10,
              ),
              //LIABILITY
              getHeader("LIABILITY"),
              SizedBox(
                height: 10,
              ),
              //OUR LIABILITY
              getHeader("OUR LIABILITY"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We shall be liable for any technical and relative issue with regard to Website (www.hibachi.in). We shall be liable to deliver your orders at the delivery location, time and date opted by you. We shall however not hold any liability for any and all products or your orders after delivery."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "However, we shall hold no liability for unforeseen circumstances, force majeure events and situations beyond our control."),
              SizedBox(
                height: 10,
              ),
              //YOUR LIABILITY
              getHeader("YOUR LIABILITY"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• You shall be liable for any and all orders placed through the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• You shall be liable for making payment for any and all orders placed by you through the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• You shall be liable in full and complete for providing accurate information including location details, pin-code, phone no, email id, name etc. while registering and placing the order through the Website (www.hibachi.in)"),
              SizedBox(
                height: 10,
              ),
              //ONLINE PAYMENT
              getHeader("ONLINE PAYMENT"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "In order to facilitate payments for the products purchased by You or ordered by you through the Website , the website offers an online payment gateway facility that will facilitate You to make payments in respect thereof the products purchased through the Website (www.hibachi.in)using net banking, credit/debit card account or any other mode acceptable and made available to the users from time to time, subject to Your complete acceptance and adherence to the terms and conditions hereof as well as the terms and conditions of the website of the payment gateway service provider/s."),
              SizedBox(
                height: 10,
              ),
              //CREDIT CARD PAYMENT
              getHeader("CREDIT CARD PAYMENT"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Your credit card details shall be transferred directly to our payment service provider for immediate authorization and are not recorded or stored in our database. Once we have received authorization from the payment service provider, we shall confirm your service order."),
              SizedBox(
                height: 10,
              ),
              //Further
              getHeader("Further:"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "1.You have categorically authorized www.hibachi.in to collect, process, facilitate and remit payments and / or electronically from other Users in respect of transactions through Payment Facility. Your relationship with www.hibachi.in is on a principal to principal basis and by accepting these Terms of Use you agree that www.hibachi.in is an independent contractor for all purposes, and does not have control of or liability for the products that are listed on www.hibachi.in that are paid for by using the Payment gateway"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "2. You understand, accept and agree that the payment facility provided by www.hibachi.in is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, collection and remittance facility for the Transactions on www.hibachi.in using the existing authorized banking infrastructure and Credit Card payment gateway networks. Further, by providing Payment Facility, www.hibachi.in is neither acting as trustees nor acting in a fiduciary capacity with respect to the Transaction or the Transaction Price"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "3. www.hibachi.in reserves the right to impose limits on the number of Transactions or Transaction Price which we may receive from on an individual Valid Credit/ Debit/ Cash Card / Valid Bank Account/ and such other infrastructure or any other financial instrument directly or indirectly through payment aggregator or through any such facility authorized by Reserve Bank of India to provide enabling support facility for collection and remittance of payment or by an individual User during any time period, and reserves the right to refuse to process Transactions exceeding such limit."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "4. www.hibachi.in reserves the right to refuse to process Transactions by Users with a prior history of questionable charges including without limitation breach of any agreements by User with www.hibachi.in or breach / violation of any law or any charges imposed by Issuing Bank or breach of any policy."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "5. In the event, www.hibachi.in is not satisfied with the creditability of the User, it will have the right to reject the receipt of / Users"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "6. www.hibachi.in may delay notifying the payment confirmation, if www.hibachi.in deems suspicious or for Users conducting high transaction volumes to ensure safety of the Transaction and Transaction Price. In addition, www.hibachi.in may hold the service and may not provide service at the request of law enforcement officials or in the event the user is engaged in any form of illegal activity."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "7. The user acknowledges that www.hibachi.in will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction / Transaction Price or any delay in processing a Transaction / Transaction Price which is beyond control of www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              //CASH ON DELIVERY (COD) ORDERS
              getHeader("CASH ON DELIVERY (COD) ORDERS"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "All cash on delivery order payments have to be made at the time of order delivery to our delivery person. The Products would be handed over to the You only after receipt of the payment for the Products."),
            ],
          ),
        ),
      ),
    );
  }
}
