import 'package:flutter/material.dart';
import '../../helpers/aboutUsContent.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text("Privacy Policy")),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(15),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              getParagraph(
                  "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "www.hibachi.in and affiliates respect your privacy. This Privacy Policy describes in brief the manner in which your data is collected and used by www.hibachi.in. You are advised to please read the Privacy Policy carefully. By accessing the website www.hibachi.in, you agree to the collection and use of your data by www.hibachi.in in the manner provided in this Privacy Policy"),
              SizedBox(
                height: 10,
              ),
              //WE WANT YOU TO
              getHeader("WE WANT YOU TO"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Feel comfortable using our web site"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Feel secure submitting information to us"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• Contact us with your questions or concerns about privacy on this site"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• Know that by using our site you are consenting to the collection of certain data"),
              SizedBox(
                height: 10,
              ),
              //WHAT INFORMATION IS, OR MAY BE, COLLECTED FROM YOU?
              getHeader("WHAT INFORMATION IS, OR MAY BE, COLLECTED FROM YOU?"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We will automatically receive and collect certain anonymous information in standard usage logs through our Web server, including computer-identification information obtained from “cookies,” sent to your browser from a"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• web server cookie stored on your hard drive"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• an IP address assigned to the computer which you use"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• the domain server through which you access our service"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• the type of computer you’re using"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• the type of web browser you’re using"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• the device id’s and other details"),
              SizedBox(
                height: 10,
              ),
              //We may collect the following sensitive personal data or information (SPDI) about you:
              getHeader(
                  "We may collect the following sensitive personal data or information (SPDI) about you:"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Name"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Address"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Email id"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Phone No"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Location Details – Google Location"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• Phone Book Contacts – for referrals or promotions"),
              SizedBox(
                height: 10,
              ),
              //We may also collect the following information:
              getHeader("We may also collect the following information:"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• about the pages you visit / access"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• the links you click on www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• the number of times you access a page on www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              //WHO COLLECTS THE INFORMATION
              getHeader("WHO COLLECTS THE INFORMATION"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Some of your sensitive personal data or information may be collected, received, possessed, stored, dealt with or handled by:"),
              SizedBox(
                height: 10,
              ),
              //M/s. HIBACHI GOURMET PRIVATE LIMITED
              getHeader("M/s. HIBACHI GOURMET PRIVATE LIMITED"),
              SizedBox(
                height: 10,
              ),
              getParagraph("# Flat No. 305, Sy No. 37 & 38, Plot No.336,"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Sree Nilayam, Manikonda, Hyderabad – 500089, Telangana, India"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We will collect anonymous traffic information from you when you access www.hibachi.in We may collect sensitive personal data or identifiable information about you only as a part of a voluntary registration process."),
              SizedBox(
                height: 10,
              ),
              //HOW IS THE INFORMATION USED?
              getHeader("HOW IS THE INFORMATION USED?"),
              SizedBox(
                height: 10,
              ),
              getParagraph("We use your sensitive personal information to:"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• help us provide personalized features"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• tailor www.hibachi.in to your interest"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• to get in touch with you when necessary"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• to provide the services requested by you"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• to preserve social history as governed by existing law or policy"),
              SizedBox(
                height: 10,
              ),
              getParagraph("We use contact information internally to:"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• direct our efforts for improvement"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Generally, we use anonymous traffic information to:"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• remind us of who you are in order to deliver to you a better and more personalized service;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• recognize your access privileges to www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• help diagnose problems with our server, www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• administer www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• track your session so that we can understand better how people use www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "DISCLOSURE POLICY IN COMPLIANCE WITH RULE 6 OF THE IT RULES 2011"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The sensitive personal data or information may be disclosed to any person, if such disclosure is required for alawful purpose connected with a function or activity of www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The sensitive personal data or information may be disclosed, where the disclosure is necessary for complianceof a legal obligation."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We do not rent, sell, publish or share your sensitive personal data and we will not disclose any of yourpersonally identifiable information unless:"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• we have your permission"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• to help investigate, prevent or take action regarding unlawful and illegal activities, suspected fraud, including cyber incidents potential threat, punishment of offences and to the safety or security of any person, violations of www.hibachi.in ‘s terms of use or to defend against legal claims;"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "• Special circumstances such as compliance with subpoenas, court orders, requests/order from legal authoritiesor law enforcement agencies requiring such disclosure"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "WHAT CHOICES ARE AVAILABLE TO YOU REGARDING COLLECTION, USE AND DISTRIBUTION OF YOUR INFORMATION?"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Sharing your sensitive personal identifiable information is entirely voluntary. You need not register with us in order to use www.hibachi.in. However, we offer some services only to visitors who register. You may opt-in or opt-out of any services. You may update your information and change your account settings at any time."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Upon request, we will remove/block your sensitive personal identifiable information from our database, thereby cancelling your registration. However, your information may remain stored in archive on our servers even after the deletion or the termination of your account."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You can accept or decline the cookies. All sites that are customizable require that you accept cookies. You also must accept cookies to register as someone for access to some of our services. For information on how to set your browser to alert you to cookies, or to reject cookies, go to http://www.cookiecentral.com/faq/."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "WHAT SECURITY PROCEDURES ARE IN PLACE TO PROTECT INFORMATION FROM LOSS, MISUSE OR ALTERATION?"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "To protect against the loss, misuse and alteration of the information under our control, and to comply with Rule 8 of IT Rules, 2011 (Reasonable security practices and procedures and sensitive personal data or information), we have in place appropriate physical, electronic, technical, operational and managerial procedures."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Our servers are accessible only to authorized personnel and your information is shared with respective personnel to complete the transaction and to provide the services requested by you."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "Although we will endeavor to safeguard the confidentiality of your sensitive personal identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By browsing, accessing, using www.hibachi.in in whatsoever manner, you agree that we shall have no liability for disclosure of your information due to errors in transmission or unauthorized acts of third parties including any cyber-attacks."),
              SizedBox(
                height: 10,
              ),
              //HOW CAN YOU CORRECT INACCURACIES IN THE INFORMATION?
              getHeader("HOW CAN YOU CORRECT INACCURACIES IN THE INFORMATION?"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "To correct or update any information you have provided during registration, you can update or correct the inaccuracies therein through your registered account. However, you shall be responsible for informing us the same."),
              SizedBox(
                height: 10,
              ),
              getParagraph("In the event of loss of access details, you may"),
              SizedBox(
                height: 10,
              ),
              getParagraph("• Send an e-mail to info@hibachi.in"),
              SizedBox(
                height: 10,
              ),
              //POLICY UPDATES
              getHeader("POLICY UPDATES"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "We reserve the right to change or update this policy at any time by placing a prominent notice on our site. Such changes shall be effective immediately upon posting the same on www.hibachi.in"),
              SizedBox(
                height: 10,
              ),
              //INTELLECTUAL PROPERTY POLICY (IP POLICY)
              getHeader("INTELLECTUAL PROPERTY POLICY (IP POLICY)"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "All existing and future Intellectual Property in the nature of unregistered or registered rights to any and all patents, copy rights, trademarks of “Hibachi”, www.hibachi.in and all Intellectual Property relating thereof shall be the sole property of HIBACHI GOURMET PRIVATE LIMITED."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "All material on the website www.hibachi.in including content, information, images, pictures are protected by copyrights, trademarks, and other intellectual property rights. Material on the website is solely for your personal, non-commercial use."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The website www.hibachi.in uses such content, information, images etc. solely for display purposes and shall have no intention in whatsoever manner to acquire any intellectual property rights belonging to third parties."),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "You acknowledge and agree not to use, reuse, and challenge any application, registration of any marks, anywhere in the world. You shall not copy, reproduce, republish, upload, post, transmit or distribute such logos, images, marks in any way, including by e-mail or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other web site or mobile or any communication device or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks, intellectual property and other proprietary rights, and is prohibited. Any use for which you receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause."),
              SizedBox(
                height: 10,
              ),
              //INTELLECTUAL PROPERTY RELATED ISSUES
              getHeader("INTELLECTUAL PROPERTY RELATED ISSUES"),
              SizedBox(
                height: 10,
              ),
              getParagraph(
                  "The website www.hibachi.in respects the intellectual property of others. In case, You feel that Your Intellectual Property Right has been infringed, You can send an email to info@hibachi.in"),
            ],
          ),
        ),
      ),
    );
  }
}
